name: bear-server
include:
  - ../network.yml
  - volumes.yaml
  - ../../secrets/nas_storage.yaml
services:
  plex:
    extends:
      file: ../service.yml
      service: base
    image: plexinc/pms-docker:latest
    container_name: plex
    hostname: plex.vip.bear-network
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-bmP5AQLsSWRNKeVWvFGx
      - ADVERTISE_IP=http://plex.waller.beartree.me:32400/
    volumes:
      - plex_config:/config
      - plex_media:/data
      - plex_logs:/config/Library/Application Support/Plex Media Server/Logs
      - /dev/shm/plex:/transcode
