name: bear-server
include:
  - ../network.yml
  - ../certbot/volumes.yaml
services:
  adguard:
    extends:
      file: ../service.yml
      service: base
    image: adguard/adguardhome
    container_name: adguard
    hostname: adguard.vip.bear-network
    ports:
      # Old-fashioned DNS
      - '53:53/udp'
      - '53:53/tcp'
      # DNS over tls
      - '853:853/tcp'
      # DoH
      - '7000:443/tcp'
      - '7000:443/udp'
    volumes:
      - adguard-workdir:/opt/adguardhome/work
      - adguard-conf:/opt/adguardhome/conf
      - certs:/etc/letsencrypt:ro
volumes:
  adguard-workdir:
  adguard-conf: