services:
  base-no-network:
    restart: unless-stopped
    stdin_open: true
    tty: true
    # Local logging driver prevents disk exhaustion if a service
    # goes crazy with spamming too many logs
    logging:
      driver: local
    environment:
      TZ: America/Los_Angeles
    extra_hosts:
      - "storage-den.vip.bear-network:192.168.1.229"
      - "homeassistant.vip.bear-network:192.168.1.41"
  base-host-network:
    extends:
      service: base-no-network
    network_mode: host
  base:
    extends:
      service: base-no-network
    networks:
      - bear-network
  base-misc:
    extends:
      service: base-no-network
    networks:
      - bear-network-misc
