name: bear-server
include:
  - ../network.yml
  - ../plex/volumes.yaml
  - ./secrets.yaml
services:
  grafana:
    extends:
      file: ../service.yml
      service: base
    image: grafana/grafana-oss:latest
    hostname: grafana.vip.bear-network
    container_name: grafana
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_PATHS_PROVISIONING: "/etc/grafana/provisioning"
    secrets:
      - influxdb-admin-token-text
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/ds.yaml
  loki:
    extends:
      file: ../service.yml
      service: base
    image: grafana/loki:latest
    container_name: loki
    hostname: loki.vip.bear-network
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki
      - ./loki-config.yaml:/etc/loki/local-config.yaml
  alloy:
    extends:
      file: ../service.yml
      service: base
    image:  grafana/alloy:latest
    container_name: alloy
    hostname: alloy.vip.bear-network
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:80",
      "--storage.path=/var/lib/alloy/data",
      "/etc/alloy/config.alloy",
    ]
    volumes:
      - alloy_data:/var/lib/alloy/data
      - ./config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
      - plex_logs:/container-logs/plex
  influxdb:
    extends:
      file: ../service.yml
      service: base
    image: influxdb:3-enterprise
    container_name: influxdb
    hostname: influxdb.vip.bear-network
    command:
      - influxdb3
      - serve
      - --node-id=primary-node
      - --cluster-id=primary-cluster
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --admin-token-file=/run/secrets/influxdb-admin-token
    healthcheck:
      test: ["CMD-SHELL", 'curl --header "Authorization: Bearer $(cat /var/run/secrets/influxdb-admin-token-text)" http://localhost:8181/health']
      interval: 10s
      timeout: 5s
      retries: 3
    environment: {}
      # uncomment to set up
      # INFLUXDB3_ENTERPRISE_LICENSE_TYPE: home
      # INFLUXDB3_ENTERPRISE_LICENSE_EMAIL: example@example.com
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
    secrets:
      - influxdb-admin-token
      - influxdb-admin-token-text
    volumes:
      - influxdb3-data:/var/lib/influxdb3
      - influxdb3-plugins:/var/lib/influxdb3/plugins
  influxdb-ui:
    extends:
      file: ../service.yml
      service: base
    image: influxdata/influxdb3-ui:latest
    container_name: influxdb-ui
    hostname: influxdb-ui.vip.bear-network
    command:
      - --mode=admin
    volumes:
      - influxdb-ui-db:/db
  telegraf:
    extends:
      file: ../service.yml
      service: base
    image: telegraf:latest
    container_name: telegraf
    hostname: telegraf.vip.bear-network
    secrets:
      - source: influxdb-admin-token-text
        target: influxdb_token
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - 988 # to read docker sock
volumes:
  grafana-data:
  loki-data:
  alloy_data:
  influxdb3-data:
  influxdb3-plugins:
  influxdb-ui-db:
