apiVersion: 1
datasources:
- name: Loki
  type: loki
  access: proxy
  orgId: 1
  url: http://loki.vip.bear-network
  editable: false
- name: Prometheus
  type: prometheus
  url: http://prometheus.vip.bear-network:9090
  access: proxy
  isDefault: true
  editable: false
