secrets:
  influxdb-admin-token:
    file: ../../secrets/influxdb-admin-token.json
  influxdb-admin-token-text:
    file: ../../secrets/influxdb-admin-token.txt
  influxdb-ui-config:
    file: ../../secrets/influxdb-ui-config.json
