name: bear-server
include:
  - ../network.yml
services:
  nut:
    extends:
      file: ../service.yml
      service: base
    image: instantlinux/nut-upsd:latest
    hostname: nut.vip.bear-network
    container_name: nut
    environment:
      - DRIVER=usbhid-ups
      - API_PASSWORD=secret
      - SECRET=secret
      - SERIAL=QA9PW7002000
    ports:
      - "3493:3493"
