name: bear-server
include:
  - ../network.yml
  - volumes.yaml
services:
  certbot:
    extends:
      file: ../service.yml
      service: base-no-network
    build: .
    container_name: certbot
    volumes:
      - certs:/etc/letsencrypt
    secrets:
      - cloudflare_credentials
    networks:
      - bear-network
secrets:
  cloudflare_credentials:
    file: ../../secrets/certbot-cloudflare-credentials.ini
