name: bear-server
include:
  - ../network.yml
  - volumes.yaml
  - ../certbot/volumes.yaml
services:
  mdns-relay:
    extends:
      file: ../service.yml
      service: base-no-network
    container_name: mdns-relay
    image: "finallychristine/docker-mdns-relay:latest"
    networks:
      - network-discovery
    extra_hosts:
      - "host.docker.internal:host-gateway"

  homeassistant:
    extends:
      file: ../service.yml
      service: base
    container_name: homeassistant
    hostname: homeassistant.vip.bear-network
    image: "ghcr.io/home-assistant/home-assistant:latest"
    networks:
      - bear-network
      - network-discovery
    volumes:
      - homeassistant-config:/config
      - ./ha-config:/config/ha-config
      - ./ha-config.yaml:/config/configuration.yaml
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    labels:
      - docker-volume-backup.stop-during-backup=true
    secrets:
      - source: homeassistant-secrets
        target: /config/secrets.yaml
    ports:
      # Sonos callback
      - "1400:1400"
      - "1401:1401"
    # To access serial USB
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mqtt:
    extends:
      file: ../service.yml
      service: base
    container_name: mqtt
    hostname: mqtt.vip.bear-network
    image: "eclipse-mosquitto:latest"
    ports:
      - "9001" # websockets
    volumes:
      - ./mqtt.conf:/mosquitto/config/mosquitto.conf
      - mqtt-data:/mosquitto/data
    secrets:
      - mqtt-password

  mqttui:
    extends:
      file: ../service.yml
      service: base
    container_name: mqttui
    hostname: mqttui.vip.bear-network
    image: "ghcr.io/thomasnordquist/mqtt-explorer:latest"
    environment:
      MQTT_EXPLORER_USERNAME: user
      MQTT_EXPLORER_PASSWORD: ed3fbf89-24bc-4593-b512-8759023f511e
    volumes:
      - mqttui-data:/app/data

  esphome:
    extends:
      file: ../service.yml
      service: base
    container_name: esphome
    hostname: esphome.vip.bear-network
    image: ghcr.io/esphome/esphome
    environment:
      ESPHOME_DASHBOARD_USE_PING: true
    volumes:
      - esphome-data:/config

  matter:
    extends:
      file: ../service.yml
      service: base
    container_name: matter
    hostname: matter.vip.bear-network
    image: ghcr.io/matter-js/python-matter-server:stable
    volumes:
      - matter-data:/data

  purpleair-to-mqtt:
    extends:
      file: ../service.yml
      service: base
    container_name: purpleair-to-mqtt
    hostname: purpleair-to-mqtt.vip.bear-network
    image: finallychristine/purpleair-to-mqtt:latest
    volumes:
      - ./purpleair2mqtt.toml:/app/config.toml
    secrets:
      - mqtt-password

volumes:
  mqtt-data:
  mqttui-data:
  matter-data:
secrets:
  homeassistant-secrets:
    file: ../../secrets/homeassistant.yaml
  mqtt-password:
    file: ../../secrets/mqtt-internal-password
