### Default HA provided things, do not touch

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


### Custom additions
mqtt: !include ha-config/mqtt.yaml
sensor: !include ha-config/sensor.yaml
template: !include ha-config/template.yaml

sonos:
  media_player:
    advertise_addr: ha.beartree.me
    # hosts:
    #   # appears to be the primairy controller?
    #   - sonos-arc.iot

prometheus:
  namespace: ha
  requires_auth: false
