# root to load CA files
# user root
persistence true
persistence_location /mosquitto/data/
persistence_file mosquitto.db
listener 1883
#require_certificate false
#cafile /etc/ssl/certs/ca-cert-ISRG_Root_X1.pem
#certfile /etc/letsencrypt/live/waller.beartree.me/fullchain.pem
#keyfile /etc/letsencrypt/live/waller.beartree.me/privkey.pem


listener 9001
protocol websockets

# allow_anonymous true # sads :(
password_file /run/secrets/mqtt-password
