name: bear-server
include:
  - ../network.yml
services:
  backups:
    extends:
      file: ../service.yml
      service: base
    image: garethgeorge/backrest:latest
    hostname: backups.vip.bear-network
    container_name: backups
    volumes:
      - backups_data:/data
      - backups_config:/config
      - backups_cache:/cache
      - backups_tmp:/tmp
    environment:
      - BACKREST_DATA=/data
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
volumes:
  backups_data:
  backups_config:
  backups_cache:
  backups_tmp:
