
stream {
    log_format ssl_info '$remote_addr [$time_local] '
                        'protocol=$ssl_protocol '
                        'cipher=$ssl_cipher '
                        'sni=$ssl_preread_server_name '
                        'client_s_dn=$ssl_client_s_dn '
                        'status=$status';

    log_format mqtt '$remote_addr [$time_local] '
                '$protocol $status $bytes_sent $bytes_received '
                '$session_time "$upstream_addr" '
                '"$upstream_bytes_sent" "$upstream_bytes_received" '
                '"$upstream_connect_time" '
                'ssl_preread_protocol=$ssl_preread_protocol '
                'ssl_preread_server_name=$ssl_preread_server_name';


    access_log /var/log/nginx/mqtt.log mqtt;
    error_log /var/log/nginx/mqtt_error.log debug;

    upstream mqtt_broker {
      server mqtt.vip.bear-network:1883 max_fails=0 resolve;
      zone mqtt 10m;
      resolver nginx-dns.vip.bear-network valid=1s;
    }


    # Unencrypted
    server {
        server_name mqtt;

        listen 1883;
        listen [::]:1883;

        proxy_pass mqtt_broker;
    }

    # SSL termination
    server {
        server_name mqtt;

        access_log /var/log/nginx/mqtt.log ssl_info;
        listen 8883 ssl;
        listen [::]:8883 ssl;

        ssl_certificate /etc/letsencrypt/live/beartree.me/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/beartree.me/privkey.pem;

        ssl_session_cache   shared:SSL:10m;
        ssl_session_timeout 10m;

        # Modern SSL ciphers and such
        ssl_protocols TLSv1.3;
        ssl_ecdh_curve X25519:prime256v1:secp384r1;
        ssl_prefer_server_ciphers off;

        proxy_pass mqtt_broker;  # Forward decrypted to Mosquitto
        proxy_connect_timeout 5s;
        proxy_timeout 1h;
    }
}
